name: Fetch-upstream
on:
  schedule:
  - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '5'

    - name: Fetch upstream (dirty hacks)
      run: |
        mv .github .github~  # hide it from git
        git reset --hard HEAD~3
        git pull git://git.savannah.gnu.org/nano.git
        mv .github~ .github

    - name: Commit this script
      run: |
        git add .
        git -c user.email='mail@beuke.org' -c user.name='Fabian Beuke' commit \
          -m 'Merge pull request #9 from davidhcefx/patch-3'
        git push --force
